NUM_GPUS: 1
DATASET:
  CROP_SIZE: 448
  SCALE_FROM: 0.9
  SCALE_TO: 1.0
TRAIN:
  BATCH_SIZE: 16
  NUM_EPOCHS: 32
  NUM_WORKERS: 8
  PRETRAIN: 5
NET:
  BACKBONE: "vgg16"
  MODEL: "ae"
  PRE_WEIGHTS_PATH: "./models/weights/vgg16_20M.pth"
  LR: 0.001
  OPT: "SGD"
  LOSS: "SoftMargin"
  WEIGHT_DECAY: 0.0005
TEST:
  METHOD: "multiscale" # multiscale | crop
  DATA_ROOT: "/fastdata/naraslanov"
  FLIP: True
  BATCH_SIZE: 8 # 4 scales, +1 flip for each
  PAD_SIZE: [768, 768]
  SCALES: [1, 0.75, 1.25, 1.5]
  FP_CUT_SCORE: 0.3
  USE_GT_LABELS: True
  BG_POW: 1
